### ISSUE TITLE
Setup a Brave-based build

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/browsertrix-browser-base#2]
Related to webrecorder/browsertrix-crawler#189, investigate setting up a build based on Brave, either using the .deb or zip releases from GH. Examine the versioning scheme that we use as well.

**Comment by tw4l** [comment]
Need to allow at minimum two options:
- Default profile with ad blocking and cookie popups blocking via easylist-cookies enabled
- Profile with ad blocking and easylist-cookies disabled

**Comment by ikreymer** [comment]
Core brave build option is setup, profiles will be at the browsertrix crawler image.
