### ISSUE TITLE
Brave ARM64 .deb files are not (yet) available in stable releases

### ISSUE THREAD

**Issue by tw4l** [webrecorder/browsertrix-browser-base#6]
Brave has only recently started publishing .deb files for ARM64 and so they are not yet available in stable releases. For context, see: https://github.com/brave/brave-browser/issues/11836.

Depending on the timing of when ARM64 support is QAed for stable Brave, we may want to limit ARM64 support to Chrome for now.

Related to #5

**Comment by tw4l** [comment]
Commit https://github.com/webrecorder/browsertrix-browser-base/commit/17fc4f96339b4b2ea13ca2f828cfba41e24e2a4c removes ARM64 as a platform for Brave CI builds for now - we will want to add it back when ARM is fully supported on Linux in Brave.

**Comment by ikreymer** [comment]
Looks like they are now there as of: https://github.com/brave/brave-browser/releases/tag/v1.47.186

Ready to be added back in?
